/******************************************************************************
 File     : NitaSocket.h
 Date     : 21.10.2002
 Comments : 

Department		Ports			Addresses							Multicast
ATC				11000-11999		192.168.01.’’ - 192.168.10.’’		234.0.1.0 - 234.0.1.255
Communication 	10000-10999		192.168.11.’’ - 192.168.20.’’		234.0.2.0 - 234.0.2.255
Planning		12000-12999		192.168.21.’’ - 192.168.30.’’		234.0.3.0 - 234.0.3.255
 
******************************************************************************/

#ifndef __NitaSocket_h
#define __NitaSocket_h

///////////////////////
// Multicast addresses:

// default multicast addresses
#define STR_DEF_MCAST_ADDR						_T("234.0.0.0")
#define STR_ADDR_MC_ATC							_T("234.0.1.0")		// ATC
#define STR_ADDR_MC_ATC_PLAY					_T("234.0.1.50")	// APC, data reproduction
#define STR_ADDR_MC_LAZ							_T("234.0.1.75")	// Engineer workstation
#define SOCK_ADDR_UDP_METEO_MULTICASTSERVER		_T("224.1.1.1")

///////////////////////
// Socket ports:

// ArmRls
#define SOCK_PORT_UDP_TIS_TIME					 5070 // file data transfer queries processing
#define SOCK_PORT_TCP_TIS_COMMANDS				 5070 // current server info
#define SOCK_PORT_TCP_TIS_LOCAL_EXCHANGE		 5071 // current server info

// TimeService
#define SOCK_PORT_UDP_TIMESERVICE_v1			 5561 // main port
#define SOCK_PORT_UDP_TIMESERVICE_v2			15561 // backup port (if main port is occupied)

// Alpha, SourceEmulator
#define SOCK_PORT_UDP_EMULATOR_CMD				11100 // commands from emulator
#define SOCK_PORT_UDP_EMULATOR_TRACK			11102 // track info from emulator
#define SOCK_PORT_UDP_EMULATOR_BEARING			11103 // track info from emulator

// FileSynchronizer
#define SOCK_PORT_UDP_FILE_TRANSFER				11110 // file data transfer
#define SOCK_PORT_TCP_FILE_TRANSFER_QUERY		11110 // file data transfer queries processing
#define SOCK_PORT_UDP_FILE_TRANSFER_SERVER		11111 // current server info
#define SOCK_PORT_UDP_FILE_TRANSFER_SERVER_FROM	11112 // for WindowsNT40 only
#define SOCK_PORT_TCP_FILE_HOOKS_INFORMER		11112 // local info transfer about file changes
#define SOCK_PORT_TCP_REG_HOOKS_INFORMER		11113 // local info transfer about registry changes
#define SOCK_PORT_UDP_FILE_TRANSFER_FROM		11114 // for WindowsNT40 only
#define SOCK_PORT_TCP_FILE_MIRROR				11114 // file mirroring to port

// Ports generated by multicast address for groups
#define SOCK_PORT_TCP_BY_MC_FIRST				17000 // generated TCP ports
#define SOCK_PORT_TCP_BY_MC_LAST				17499 // generated TCP ports

// Logger
#define SOCK_PORT_UDP_LOGGER					11120 // UDP port for log messages
#define SOCK_PORT_TCP_LOGGER_QUERY				11120 // local log requests

// IP hosts (exec)
#define SOCK_PORT_TCP_HOST_REQUEST				11125 // port for TCP requests
#define SOCK_PORT_UDP_HOST_RESPONDER			11125 // port for UDP requests
#define SOCK_PORT_UDP_HOST_RECEIVER				11126 // port for UDP answers

// ip_st
#define SOCK_PORT_UDP_IPST_CONTROL				11130 // UDP port for control packets exchange
#define SOCK_PORT_UDP_IPST_SRVR					11131 // UDP port for server election
#define SOCK_PORT_UDP_IPST_CONTROL_ANS			11132 // UDP port for answer on control packet requests
//
#define SOCK_PORTS_IPST_DATA_CHANNELS			  100 // number of UDP port for data packets
#define SOCK_PORT_UDP_IPST_CHANNEL_FIRST		11200 // first UDP port for data packets
#define SOCK_PORT_UDP_IPST_CHANNEL_LAST			11299 // last  UDP port for data packets
#define SOCK_PORT_UDP_IPST_CH_PLAY_FIRST		11300 // first UDP port for data packets (play mode)
#define SOCK_PORT_UDP_IPST_CH_PLAY_LAST			11399 // last  UDP port for data packets (play mode)

// GrnRecorder
#define SOCK_PORT_TCP_GRN_RECORDER_FIRST		11900 // channels of data transfer from Alpha to Granite
#define SOCK_PORT_TCP_GRN_RECORDER_LAST			11999

// Engineer workstation
#define SOCK_PORT_UDP_LAZ						20000 // Engineer workstation
#define SOCK_PORT_TCP_LAZ						20001 // ¿Engineer workstation
#define SOCK_PORT_TCP_LAZ_LOCAL_EXCHANGE		20002 // Engineer workstation, local data exchange

// Alpha, SourceEmulator
#define SOCK_PORT_UDP_RAY_EMULATOR_BASE			31100 // ray info from emulator: port = BASE + RadarID
#define SOCK_PORT_UDP_RAY_BASE					31120 // real ray info: port = BASE + RadarID
#define SOCK_PORT_UDP_RAY_BASE_LAST				31139
//
#define SOCK_PORT_TCP_METEO_LOCAL				33101
#define SOCK_PORT_UDP_METEO_SERVER				33121
#define SOCK_PORT_UDP_FROMMETEOEXTSERVER		33130
#define SOCK_PORT_UDP_TOMETEOEXTSERVER			33131

#endif // __NitaSocket_h
